// Code generated by protoc-gen-go.
// source: kvs/kvs.proto
// DO NOT EDIT!

/*
Package kvs is a generated protocol buffer package.

It is generated from these files:
	kvs/kvs.proto

It has these top-level messages:
	Key
	Value
	Entry
	PutResponse
	DeleteResponse
	ListRequest
*/
package kvs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Key defines a simple key in the KVS.
type Key struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Value represents a share in SSS.
type Value struct {
	Field  string   `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Key    string   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Shares []string `protobuf:"bytes,3,rep,name=shares" json:"shares,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Value) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *Value) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Value) GetShares() []string {
	if m != nil {
		return m.Shares
	}
	return nil
}

// Entry defines a pair of key and value as an entry in the KVS.
type Entry struct {
	Key   *Key   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Entry) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

// Define empty requests/responses.
type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Key)(nil), "kvs.Key")
	proto.RegisterType((*Value)(nil), "kvs.Value")
	proto.RegisterType((*Entry)(nil), "kvs.Entry")
	proto.RegisterType((*PutResponse)(nil), "kvs.PutResponse")
	proto.RegisterType((*DeleteResponse)(nil), "kvs.DeleteResponse")
	proto.RegisterType((*ListRequest)(nil), "kvs.ListRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kvs service

type KvsClient interface {
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error)
	Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DeleteResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Kvs_ListClient, error)
}

type kvsClient struct {
	cc *grpc.ClientConn
}

func NewKvsClient(cc *grpc.ClientConn) KvsClient {
	return &kvsClient{cc}
}

func (c *kvsClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := grpc.Invoke(ctx, "/kvs.Kvs/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Put(ctx context.Context, in *Entry, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/kvs.Kvs/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := grpc.Invoke(ctx, "/kvs.Kvs/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvsClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (Kvs_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Kvs_serviceDesc.Streams[0], c.cc, "/kvs.Kvs/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &kvsListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kvs_ListClient interface {
	Recv() (*Key, error)
	grpc.ClientStream
}

type kvsListClient struct {
	grpc.ClientStream
}

func (x *kvsListClient) Recv() (*Key, error) {
	m := new(Key)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Kvs service

type KvsServer interface {
	Get(context.Context, *Key) (*Value, error)
	Put(context.Context, *Entry) (*PutResponse, error)
	Delete(context.Context, *Key) (*DeleteResponse, error)
	List(*ListRequest, Kvs_ListServer) error
}

func RegisterKvsServer(s *grpc.Server, srv KvsServer) {
	s.RegisterService(&_Kvs_serviceDesc, srv)
}

func _Kvs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvs.Kvs/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvs.Kvs/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Put(ctx, req.(*Entry))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvs.Kvs/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvsServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvs_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KvsServer).List(m, &kvsListServer{stream})
}

type Kvs_ListServer interface {
	Send(*Key) error
	grpc.ServerStream
}

type kvsListServer struct {
	grpc.ServerStream
}

func (x *kvsListServer) Send(m *Key) error {
	return x.ServerStream.SendMsg(m)
}

var _Kvs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvs.Kvs",
	HandlerType: (*KvsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Kvs_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Kvs_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kvs_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Kvs_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvs/kvs.proto",
}

func init() { proto.RegisterFile("kvs/kvs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x4d, 0xdc, 0xa6, 0xd8, 0x09, 0x91, 0x30, 0x8a, 0xc4, 0x80, 0x10, 0x16, 0x94, 0x7a, 0xa9,
	0x12, 0xff, 0x82, 0xa5, 0x87, 0x78, 0x28, 0x39, 0x78, 0x8f, 0x38, 0x62, 0x49, 0x4c, 0x6a, 0x66,
	0xb3, 0x90, 0x3f, 0xe3, 0x6f, 0x95, 0xdd, 0x2d, 0x21, 0x78, 0x7b, 0xf3, 0x1e, 0xef, 0x03, 0x06,
	0xa2, 0x5a, 0xf3, 0x63, 0xad, 0x79, 0x73, 0xec, 0x3b, 0xd5, 0xa1, 0xa8, 0x35, 0xcb, 0x1b, 0x10,
	0x05, 0x8d, 0x88, 0xb0, 0x68, 0xab, 0x6f, 0x4a, 0xfc, 0xcc, 0x5f, 0xaf, 0x4a, 0x8b, 0xe5, 0x0e,
	0x82, 0xb7, 0xaa, 0x19, 0x08, 0xaf, 0x20, 0xf8, 0x3c, 0x50, 0xf3, 0x71, 0x52, 0xdd, 0x81, 0x31,
	0x88, 0x9a, 0xc6, 0xe4, 0xcc, 0x72, 0x06, 0xe2, 0x35, 0x2c, 0xf9, 0xab, 0xea, 0x89, 0x13, 0x91,
	0x89, 0xf5, 0xaa, 0x3c, 0x5d, 0x72, 0x0b, 0xc1, 0xb6, 0x55, 0xfd, 0x88, 0xa9, 0xb3, 0x98, 0x98,
	0x30, 0x3f, 0xdf, 0x98, 0x29, 0x05, 0x8d, 0xce, 0x9c, 0x41, 0xa0, 0x4d, 0x9b, 0x0d, 0x0c, 0x73,
	0xb0, 0xaa, 0xed, 0x2f, 0x9d, 0x20, 0x23, 0x08, 0xf7, 0x83, 0x2a, 0x89, 0x8f, 0x5d, 0xcb, 0x24,
	0x63, 0xb8, 0x78, 0xa1, 0x86, 0x14, 0x4d, 0x4c, 0x04, 0xe1, 0xeb, 0x81, 0x55, 0x49, 0x3f, 0x03,
	0xb1, 0xca, 0x7f, 0x7d, 0x10, 0x85, 0x66, 0xbc, 0x05, 0xb1, 0x23, 0x85, 0x53, 0x5f, 0x3a, 0xcb,
	0x96, 0x1e, 0xde, 0x81, 0xd8, 0x0f, 0x0a, 0x1d, 0x69, 0x77, 0xa6, 0xb1, 0xc5, 0xf3, 0x32, 0x0f,
	0x1f, 0x60, 0xe9, 0xea, 0x66, 0x41, 0x97, 0x16, 0xfd, 0x5b, 0xe1, 0xe1, 0x3d, 0x2c, 0xcc, 0x0e,
	0x74, 0x31, 0xb3, 0x49, 0xe9, 0x64, 0x95, 0xde, 0x93, 0xff, 0xbe, 0xb4, 0x7f, 0x78, 0xfe, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xa2, 0x60, 0xc3, 0x05, 0x98, 0x01, 0x00, 0x00,
}
